# coding: utf-8

# flake8: noqa
"""
    Onezone

    # Overview This is the RESTful API definition of Onezone component of Onedata data management system [onedata.org](http://onedata.org).  > This API is defined using [Swagger](http://swagger.io/), the JSON specification can be used to automatically generate client libraries - [swagger.json](../../../swagger/onezone/swagger.json).  This API allows control and configuration of local Onezone service deployment, in particular management of users, groups, spaces, shares, providers, handle services, handles and clusters.  ## Authentication and authorization To be able to use this API, the REST client must authenticate with the Onezone service and posses required authorization, which is determined based on client's privileges and relations in the system.  There are essentially three types of REST clients depending on the authentication:   * **users** - can authenticate using an access token or basic credentials   (only for users originating from Onezone's onepanel). Examples:   ```bash   curl -H \"x-auth-token: $TOKEN\" [...]   curl -H \"authorization: Bearer $TOKEN\" [...]   curl -u \"username:password\" [...]   curl -H \"macaroon: $TOKEN\" [...]   # DEPRECATED   ```   > `$TOKEN` can ba a Onedata access token, obtained via Onezone GUI or API, in the form   `MDAxNWxvY2F00aW9...`. If authority delegation for given IdP is enabled,   it is possible to provide an access token from the IdP, which must be prefixed   properly (depending on the configuration), e.g.: `github/GST5aasdA...`.    * **Oneproviders** - can authenticate using the provider root token,   which was assigned during registration in Onezone. It can be found in   `/etc/op_worker/provider_root_token.txt`. It is used just like a user   access token, for example:   ```bash   curl -H \"x-auth-token: $TOKEN\" [...]   curl -H \"authorization: Bearer $TOKEN\" [...]   curl -H \"macaroon: $TOKEN\" [...]   # DEPRECATED   ```   > Please mind that the provider root token is highly confidential and must   be kept secret (similarly to a private RSA key).    * **anonymous** - there is a small subset of operations that do not require     any authentication and are publicly available (look for information about     public availability in the endpoint descriptions).  The authorization of the client is determined based on existing relations and privileges in the system. In most cases, the rules below can be roughly applied:   * users and providers can access and modify their own data   * users can perform operations in groups, spaces, handle services, handles     and clusters depending on their privileges in subject entity - the required     privileges are listed in the description of each operation   * users can be given special admin privileges (fine-grained) that allow to     access and modify all entities in the system - see certain operations for     details.  Authentication and Authorization errors have the following meaning:   * HTTP 401 UNAUTHORIZED - the client could not be authenticated   * HTTP 403 FORBIDDEN - the client was authenticated, but is not permitted to     perform the action  ## Effective users and effective groups and spaces Onedata supports creation of arbitrary nested group and space membership tree structures. In order to determine if a given user belongs to the group directly or indirectly by belonging to a subgroup of a group, separate API calls are provided for getting information about group users (direct group members) and effective users (indirect group members).  ## API structure The API is divided into several categories, corresponding to entities in Onedata:  **Space management** The space management operations of this API provide means for accessing information about spaces and their management.  **Share management** The share management operations of this API provide means for accessing information about shares and their management.  **Group management** The group management operations allow creation of user groups, assigning their authorization rights, adding and removing users from groups.  **User management** The user management methods allow creation of users, managing their authorization credentials as well as space and group membership.  **Provider management** Provider specific calls allow getting global information about the spaces managed by the provider, and some administrative operations which can be used for monitoring or accounting.  **Handle service management** The handle service management operations of this API provide means for accessing information about handle services and their management.  **Handle API** Onezone provides extensive support for integration with Handle system registration services, including support for DOI and PID identifier assignment services. The API provides methods for adding new Handle services to the system, managing which users can use which registration services and complete API for registering identifiers to users' data sets which are made public.  **Cluster management** Operations for managing Onezone / Oneprovider clusters and their members - users and groups that can access the Onepanel interfaces (REST or GUI) of a cluster.   ## Using the API Onezone API is quite complex and thus it might be difficult to quickly figure out how to perform specific action, however the following guidelines might be useful:   * Operations performed by a regular users on their resources are grouped under     `/user` path (**USER** group in the menu)   * Operations performed by administrators of specific resources (e.g. groups,     spaces, shares) start with specific resource (e.g. `/groups`)   * By default the operations which list resource membership     (e.g. `/spaces/SPACE_ID/groups/`) will list explicit resource membership.     To get list of effective resource membership (i.e. including indirect     membership), special paths are provided     (e.g. `/spaces/SPACE_ID/effective_groups/`)  Furthermore, we have prepared a command-line client environment based on Docker which gives easy access to each of Onedata services via command-line clients, with pre-configured shell with full help on the APIs and autocomplete for operations and attributes.  ``` docker run -it onedata/rest-cli:21.02.3 ```  Below you can find some tutorials which show how to use this API in practice:   * [User oriented tutorial](https://onedata.org/#/home/documentation/doc/using_onedata/using_onedata_from_cli.html)   * [Administrator oriented tutorial](https://onedata.org/#/home/documentation/doc/administering_onedata/administering_onedata_from_cli.html)   ## Examples  **Generate new authentication token** ```bash curl -u user:password -X POST -H 'Content-type: application/json' -d '{}' \\ https://$ONEZONE_HOST/api/v3/onezone/user/client_tokens ```  **Get user details** ```bash curl -H 'X-Auth-Token: $TOKEN' -X GET \\ https://$ONEZONE_HOST/api/v3/onezone/user ```  **Get user details using an access token from github** ```bash curl -H 'X-Auth-Token: github/ijaAVWq3j9234jA9gPoR9agFja89t9UiPf8tiueSdx' -X GET \\ https://$ONEZONE_HOST/api/v3/onezone/user ``` > Note that GitHub IdP must be properly configured for the example to work: > * authority delegation must be enabled > * tokenPrefix must be set to \"github/\" > > You can learn more in > [the documentation](https://onedata.org/#/home/documentation/doc/administering_onedata/openid_saml_configuration/openid_saml_configuration_19_02[authority-delegation].html).   # noqa: E501

    OpenAPI spec version: 21.02.3
    Contact: info@onedata.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from onezone_client.models.admin_privileges import AdminPrivileges
from onezone_client.models.admin_privileges_update import AdminPrivilegesUpdate
from onezone_client.models.api import Api
from onezone_client.models.asn import Asn
from onezone_client.models.caveat import Caveat
from onezone_client.models.children_cid_body import ChildrenCidBody
from onezone_client.models.client_token import ClientToken
from onezone_client.models.client_tokens import ClientTokens
from onezone_client.models.cluster import Cluster
from onezone_client.models.cluster_invite_token import ClusterInviteToken
from onezone_client.models.cluster_manager_privileges import ClusterManagerPrivileges
from onezone_client.models.cluster_member_privileges import ClusterMemberPrivileges
from onezone_client.models.cluster_privileges import ClusterPrivileges
from onezone_client.models.cluster_privileges_update import ClusterPrivilegesUpdate
from onezone_client.models.cluster_update_request import ClusterUpdateRequest
from onezone_client.models.clusters import Clusters
from onezone_client.models.configuration import Configuration
from onezone_client.models.configuration_supported_id_ps import ConfigurationSupportedIdPs
from onezone_client.models.consumer import Consumer
from onezone_client.models.doi_service_properties import DOIServiceProperties
from onezone_client.models.doi_service_properties_update import DOIServicePropertiesUpdate
from onezone_client.models.data_objectid import DataObjectid
from onezone_client.models.data_path import DataPath
from onezone_client.models.data_readonly import DataReadonly
from onezone_client.models.error import Error
from onezone_client.models.error_error import ErrorError
from onezone_client.models.examined_token import ExaminedToken
from onezone_client.models.geo_country import GeoCountry
from onezone_client.models.geo_region import GeoRegion
from onezone_client.models.group import Group
from onezone_client.models.group_create_request import GroupCreateRequest
from onezone_client.models.group_invite_token import GroupInviteToken
from onezone_client.models.group_join_cluster import GroupJoinCluster
from onezone_client.models.group_join_group import GroupJoinGroup
from onezone_client.models.group_join_harvester import GroupJoinHarvester
from onezone_client.models.group_join_space import GroupJoinSpace
from onezone_client.models.group_manager_privileges import GroupManagerPrivileges
from onezone_client.models.group_member_privileges import GroupMemberPrivileges
from onezone_client.models.group_privileges import GroupPrivileges
from onezone_client.models.group_privileges_update import GroupPrivilegesUpdate
from onezone_client.models.group_update_request import GroupUpdateRequest
from onezone_client.models.groups import Groups
from onezone_client.models.groups_gid_body import GroupsGidBody
from onezone_client.models.groups_gid_body1 import GroupsGidBody1
from onezone_client.models.groups_gid_body2 import GroupsGidBody2
from onezone_client.models.groups_gid_body3 import GroupsGidBody3
from onezone_client.models.groups_gid_body4 import GroupsGidBody4
from onezone_client.models.handle import Handle
from onezone_client.models.handle_member_privileges import HandleMemberPrivileges
from onezone_client.models.handle_privileges import HandlePrivileges
from onezone_client.models.handle_privileges_update import HandlePrivilegesUpdate
from onezone_client.models.handle_registration_request import HandleRegistrationRequest
from onezone_client.models.handle_service import HandleService
from onezone_client.models.handle_service_create_request import HandleServiceCreateRequest
from onezone_client.models.handle_service_member_privileges import HandleServiceMemberPrivileges
from onezone_client.models.handle_service_privileges import HandleServicePrivileges
from onezone_client.models.handle_service_privileges_update import HandleServicePrivilegesUpdate
from onezone_client.models.handle_service_properties import HandleServiceProperties
from onezone_client.models.handle_service_properties_update import HandleServicePropertiesUpdate
from onezone_client.models.handle_service_update import HandleServiceUpdate
from onezone_client.models.handle_services import HandleServices
from onezone_client.models.handles import Handles
from onezone_client.models.handles_id_body import HandlesIdBody
from onezone_client.models.harvester import Harvester
from onezone_client.models.harvester_create_request import HarvesterCreateRequest
from onezone_client.models.harvester_gui_plugin_config import HarvesterGuiPluginConfig
from onezone_client.models.harvester_index import HarvesterIndex
from onezone_client.models.harvester_index_create_request import HarvesterIndexCreateRequest
from onezone_client.models.harvester_index_stats_details import HarvesterIndexStatsDetails
from onezone_client.models.harvester_index_stats_details_space_id import HarvesterIndexStatsDetailsSpaceId
from onezone_client.models.harvester_index_stats_details_space_id_provider_id import HarvesterIndexStatsDetailsSpaceIdProviderId
from onezone_client.models.harvester_indices import HarvesterIndices
from onezone_client.models.harvester_invite_token import HarvesterInviteToken
from onezone_client.models.harvester_join_space import HarvesterJoinSpace
from onezone_client.models.harvester_manager_privileges import HarvesterManagerPrivileges
from onezone_client.models.harvester_member_privileges import HarvesterMemberPrivileges
from onezone_client.models.harvester_privileges import HarvesterPrivileges
from onezone_client.models.harvester_privileges_update import HarvesterPrivilegesUpdate
from onezone_client.models.harvester_query import HarvesterQuery
from onezone_client.models.harvester_query_response import HarvesterQueryResponse
from onezone_client.models.harvester_update_request import HarvesterUpdateRequest
from onezone_client.models.harvesters import Harvesters
from onezone_client.models.id_p_access_token import IdPAccessToken
from onezone_client.models.id_request_body import IdRequestBody
from onezone_client.models.id_spaces_body import IdSpacesBody
from onezone_client.models.indices_idx_body import IndicesIdxBody
from onezone_client.models.inline_response200 import InlineResponse200
from onezone_client.models.inline_response2001 import InlineResponse2001
from onezone_client.models.inline_response20010 import InlineResponse20010
from onezone_client.models.inline_response20011 import InlineResponse20011
from onezone_client.models.inline_response20012 import InlineResponse20012
from onezone_client.models.inline_response20013 import InlineResponse20013
from onezone_client.models.inline_response20014 import InlineResponse20014
from onezone_client.models.inline_response20015 import InlineResponse20015
from onezone_client.models.inline_response20016 import InlineResponse20016
from onezone_client.models.inline_response20017 import InlineResponse20017
from onezone_client.models.inline_response20018 import InlineResponse20018
from onezone_client.models.inline_response20019 import InlineResponse20019
from onezone_client.models.inline_response2002 import InlineResponse2002
from onezone_client.models.inline_response20020 import InlineResponse20020
from onezone_client.models.inline_response2003 import InlineResponse2003
from onezone_client.models.inline_response2004 import InlineResponse2004
from onezone_client.models.inline_response2005 import InlineResponse2005
from onezone_client.models.inline_response2006 import InlineResponse2006
from onezone_client.models.inline_response2007 import InlineResponse2007
from onezone_client.models.inline_response2007_spaces import InlineResponse2007Spaces
from onezone_client.models.inline_response2008 import InlineResponse2008
from onezone_client.models.inline_response2009 import InlineResponse2009
from onezone_client.models.interface import Interface
from onezone_client.models.invite_token import InviteToken
from onezone_client.models.invite_token_property_privileges import InviteTokenPropertyPrivileges
from onezone_client.models.invite_token_property_usage_limit import InviteTokenPropertyUsageLimit
from onezone_client.models.ip import Ip
from onezone_client.models.linked_account import LinkedAccount
from onezone_client.models.marketplace_list_body import MarketplaceListBody
from onezone_client.models.membership_intermediaries import MembershipIntermediaries
from onezone_client.models.membership_intermediaries_intermediaries import MembershipIntermediariesIntermediaries
from onezone_client.models.named_token import NamedToken
from onezone_client.models.named_token_create_request import NamedTokenCreateRequest
from onezone_client.models.named_token_create_response import NamedTokenCreateResponse
from onezone_client.models.named_token_status import NamedTokenStatus
from onezone_client.models.named_token_update_request import NamedTokenUpdateRequest
from onezone_client.models.pid_service_properties import PIDServiceProperties
from onezone_client.models.pid_service_properties_update import PIDServicePropertiesUpdate
from onezone_client.models.provider_details import ProviderDetails
from onezone_client.models.provider_domain_config import ProviderDomainConfig
from onezone_client.models.provider_registration_request import ProviderRegistrationRequest
from onezone_client.models.provider_registration_response import ProviderRegistrationResponse
from onezone_client.models.provider_registration_token import ProviderRegistrationToken
from onezone_client.models.provider_sync_progress import ProviderSyncProgress
from onezone_client.models.provider_sync_progress_additional_properties import ProviderSyncProgressAdditionalProperties
from onezone_client.models.provider_update_request import ProviderUpdateRequest
from onezone_client.models.providers import Providers
from onezone_client.models.public_map_idp_group_body import PublicMapIdpGroupBody
from onezone_client.models.public_map_idp_user_body import PublicMapIdpUserBody
from onezone_client.models.public_verify_provider_identity_body import PublicVerifyProviderIdentityBody
from onezone_client.models.register_oneprovider import RegisterOneprovider
from onezone_client.models.rid_resolve_body import RidResolveBody
from onezone_client.models.serialized_token import SerializedToken
from onezone_client.models.service import Service
from onezone_client.models.share import Share
from onezone_client.models.shares import Shares
from onezone_client.models.shares_id_body import SharesIdBody
from onezone_client.models.space import Space
from onezone_client.models.space_advertised_in_marketplace import SpaceAdvertisedInMarketplace
from onezone_client.models.space_alias import SpaceAlias
from onezone_client.models.space_create_request import SpaceCreateRequest
from onezone_client.models.space_description import SpaceDescription
from onezone_client.models.space_invite_token import SpaceInviteToken
from onezone_client.models.space_join_harvester import SpaceJoinHarvester
from onezone_client.models.space_manager_privileges import SpaceManagerPrivileges
from onezone_client.models.space_marketplace_contact_email import SpaceMarketplaceContactEmail
from onezone_client.models.space_marketplace_data import SpaceMarketplaceData
from onezone_client.models.space_member_privileges import SpaceMemberPrivileges
from onezone_client.models.space_membership_request import SpaceMembershipRequest
from onezone_client.models.space_membership_requester_info import SpaceMembershipRequesterInfo
from onezone_client.models.space_membership_requests import SpaceMembershipRequests
from onezone_client.models.space_organization_name import SpaceOrganizationName
from onezone_client.models.space_privileges import SpacePrivileges
from onezone_client.models.space_privileges_update import SpacePrivilegesUpdate
from onezone_client.models.space_stats import SpaceStats
from onezone_client.models.space_support_token import SpaceSupportToken
from onezone_client.models.space_tags import SpaceTags
from onezone_client.models.spaces import Spaces
from onezone_client.models.spaces_body import SpacesBody
from onezone_client.models.spaces_id_body import SpacesIdBody
from onezone_client.models.subject import Subject
from onezone_client.models.support_parameters import SupportParameters
from onezone_client.models.support_space import SupportSpace
from onezone_client.models.support_stage_details import SupportStageDetails
from onezone_client.models.temporary_token_create_request import TemporaryTokenCreateRequest
from onezone_client.models.temporary_token_generation import TemporaryTokenGeneration
from onezone_client.models.time import Time
from onezone_client.models.timestamp import Timestamp
from onezone_client.models.token_property_caveats import TokenPropertyCaveats
from onezone_client.models.token_property_custom_metadata import TokenPropertyCustomMetadata
from onezone_client.models.token_property_id import TokenPropertyId
from onezone_client.models.token_property_metadata import TokenPropertyMetadata
from onezone_client.models.token_property_name import TokenPropertyName
from onezone_client.models.token_property_onezone_domain import TokenPropertyOnezoneDomain
from onezone_client.models.token_property_persistence import TokenPropertyPersistence
from onezone_client.models.token_property_revoked import TokenPropertyRevoked
from onezone_client.models.token_property_subject import TokenPropertySubject
from onezone_client.models.token_property_token_type import TokenPropertyTokenType
from onezone_client.models.tokens import Tokens
from onezone_client.models.tokens_confine_body import TokensConfineBody
from onezone_client.models.tokens_examine_body import TokensExamineBody
from onezone_client.models.user import User
from onezone_client.models.user_access_block_update import UserAccessBlockUpdate
from onezone_client.models.user_basic_auth_settings_update import UserBasicAuthSettingsUpdate
from onezone_client.models.user_create_request import UserCreateRequest
from onezone_client.models.user_join_cluster import UserJoinCluster
from onezone_client.models.user_join_group import UserJoinGroup
from onezone_client.models.user_join_harvester import UserJoinHarvester
from onezone_client.models.user_join_space import UserJoinSpace
from onezone_client.models.user_password_update import UserPasswordUpdate
from onezone_client.models.user_protected_info import UserProtectedInfo
from onezone_client.models.user_update_request import UserUpdateRequest
from onezone_client.models.users import Users
from onezone_client.models.users_uid_body import UsersUidBody
from onezone_client.models.users_uid_body1 import UsersUidBody1
from onezone_client.models.users_uid_body2 import UsersUidBody2
from onezone_client.models.users_uid_body3 import UsersUidBody3
from onezone_client.models.users_uid_body4 import UsersUidBody4
from onezone_client.models.users_uid_body5 import UsersUidBody5
from onezone_client.models.verify_access_token_request import VerifyAccessTokenRequest
from onezone_client.models.verify_identity_token_request import VerifyIdentityTokenRequest
from onezone_client.models.verify_invite_token_request import VerifyInviteTokenRequest
from onezone_client.models.verify_token_response import VerifyTokenResponse
from onezone_client.models.version_info import VersionInfo
from onezone_client.models.viewer_privileges import ViewerPrivileges
